build: 
  os: ubuntu-24.04
  tools:
    python: "3.12" 

formats:
  - epub
  - htmlzip
  - pdf

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/src/conf.py

version: 2
