[global]
system_type = "server" # server | desktop
server_role = ""

[global.package.manager]
amzn.manager = 'dnf'
amzn.installed = ['dnf', 'list', '--installed']
amzn.uninstall = ['dnf', 'remove']
centos.manager = 'yum'
centos.installed = ['yum', 'list']
centos.uninstall = ['yum', 'remove']
debian.manager = 'apt'
debian.installed = ['apt', 'list']
debian.uninstall = ['apt', 'remove']
fedora.manager = 'dnf'
fedora.installed = ['dnf', 'list', '--installed']
fedora.uninstall = ['dnf', 'remove']
# rhel.manager = ''
# rhel.installed = []
# rhel.uninstall = []
# sles.manager = ''
# sles.installed = []
# sles.uninstall = []
ubuntu.manager = 'apt'
ubuntu.installed = ['apt', 'list']
ubuntu.uninstall = ['apt', 'remove']
