[global]

[global.amzn]
package_install = ["install"]
package_remove = ["remove"]
# package_search = ["rpm", "-q"]
package_search = ["dnf", "list", "installed"]

[global.debian]
package_install = ["install"]
package_remove = ["remove"]
package_search = ["search"]

[global.kali]
package_install = ["install"]
package_remove = ["remove"]
package_search = ["search"]

[global.ubuntu]
package_install = ["install"]
package_remove = ["remove"]
package_search = ["dpkg-query", "-s"]

logging_service = "rsyslog"
time_service = "chrony"

# Old code

# amzn.installed = ['dnf', 'list', '--installed']
# amzn.uninstall = ['dnf', 'remove']
# debian.installed = ['dpkg', '--list']
# debian.uninstall = ['apt', 'remove']
# kali.installed = ['dpkg', '--list']
# kali.uninstall = ['apt', 'remove']
# ubuntu.installed = ['dpkg', '--list']
# ubuntu.uninstall = ['apt', 'remove']
