[pkgmgr]
amzn.installed = ['dnf', 'list', '--installed']
amzn.uninstall = ['dnf', 'remove']
debian.installed = ['dpkg', '--list']
debian.uninstall = ['apt', 'remove']
fedora.installed = ['dnf', 'list', '--installed']
fedora.uninstall = ['dnf', 'remove']
kali.installed = ['dpkg', '--list']
kali.uninstall = ['apt', 'remove']
ubuntu.installed = ['dpkg', '--list']
ubuntu.uninstall = ['apt', 'remove']
# rhel.installed = []
# rhel.uninstall = []
# sles.installed = []
# sles.uninstall = []

[ssh]
config = "/etc/ssh/ssh_config"
path = "/etc/ssh/ssh_config.d"

[sshd]
config = "/etc/ssh/sshd_config"
path = "/etc/ssh/sshd_config.d"
