#################################################
# Global Configuration
#################################################
[global]
# modprobe Configuration File Locations
modprobe_config = "/etc/modprobe.d/"
# modprobe_fs_config = "uncommon-fs.conf"

#################################################
# Filesystems Configuration
#################################################
[filesystems.cramfs]
disable = true
cis = "level-2"
stig = ""

[filesystems.fat]
disable = false
cis = ""
stig = ""

[filesystems.freevxfs]
disable = true
cis = "level-1"
stig = ""

[filesystems.gfs2]
disable = false
cis = ""
stig = ""

[filesystems.hfs]
disable = true
cis = "level-1"
stig = ""

[filesystems.hfsplus]
disable = true
cis = "level-1"
stig = ""

[filesystems.jffs2]
disable = true
cis = "level-1"
stig = ""

[filesystems.nfs]
disable = false
cis = ""
stig = ""

[filesystems.nfsv3]
disable = false
cis = ""
stig = ""

[filesystems.squashfs]
disable = true
cis = "level-2"
stig = ""

[filesystems.udf]
disable = true
cis = "level-2"
stig = ""

[filesystems.vfat]
disable = false
cis = ""
stig = ""
