[global]
system_type = "server" # server | desktop
server_role = ""

[global.package.manager]
amzn.manager = 'dnf'
amzn.installed = ['dnf', 'list', '--installed']
amzn.uninstall = ['dnf', 'remove']
centos.manager = 'yum'
centos.installed = ['yum', 'list']
centos.uninstall = ['yum', 'remove']
debian.manager = 'apt'
debian.installed = ['apt', 'list']
debian.uninstall = ['apt', 'remove']
fedora.manager = 'dnf'
fedora.installed = ['dnf', 'list', '--installed']
fedora.uninstall = ['dnf', 'remove']
rhel.manager = ''
rhel.installed = []
rhel.uninstall = []
sles.manager = ''
sles.installed = []
sles.uninstall = []
ubuntu.manager = 'apt'
ubuntu.installed = ['apt', 'list']
ubuntu.uninstall = ['apt', 'remove']

[packages]
category_audit = true
category_harden = true
category_name = "Packages"

[packages.gpg]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Gpg"

[packages.audit]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Audit"

[packages.audit.audit]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package audit"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "audit"
package_install = true

[packages.audit.auditd]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package auditd"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "auditd"
package_install = true

[packages.audit.audispd-plugins]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package audispd-plugins"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "audispd-plugins"
package_install = true

[packages.client]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Client"

[packages.client.openldap-clients]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package openldap-clients"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "openldap-clients"
package_install = false

[packages.client.ldap-utils]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package ldap-utils"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "ldap-utils"
package_install = false

[packages.client.telnet]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package telnet"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "telnet"
package_install = false

[packages.desktop]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Desktop"

[packages.firewall]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Firewall"

[packages.firewall.nftables]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package nftables"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "nftables"
package_install = true

[packages.log]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Log"

[packages.log.rsyslog]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package rsyslog"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "rsyslog"
package_install = true

[packages.log.systemd-journal-remote]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package systemd-journal-remote"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "systemd-journal-remote"
package_install = true

[packages.security]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Security"

[packages.security.aide]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package aide"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "aide"
package_install = true

[packages.security.authselect]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package authselect"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "authselect"
package_install = true

[packages.security.libselinux]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package libselinux"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "libselinux"
package_install = true

[packages.security.libselinux1]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package libselinux1"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "libselinux1"
package_install = false

[packages.security.apparmor]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package apparmor"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "apparmor"
package_install = false

[packages.security.sudo]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package sudo"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "sudo"
package_install = true

[packages.service]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Service"

[packages.service.at]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package at"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "at"
package_install = true

[packages.service.avahi]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package avahi"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "avahi"
package_install = false

[packages.service.avahi-daemon]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package avahi-daemon"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "avahi-daemon"
package_install = false

[packages.service.bind]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package bind"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "bind"
package_install = false

[packages.service.bind9]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package bind9"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "bind9"
package_install = false

[packages.service.cronie]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package cronie"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "cronie"
package_install = true

[packages.service.cron]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package cron"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "cron"
package_install = true

[packages.service.cups]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package cups"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "cups"
package_install = false

[packages.service.dnsmasq]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package dnsmasq"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "dnsmasq"
package_install = false

[packages.service.dovecot]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package dovecot"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "dovecot"
package_install = false

[packages.service.dovecot-pop3d]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package dovecot-pop3d"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "dovecot-pop3d"
package_install = false

[packages.service.httpd]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package httpd"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "httpd"
package_install = false

[packages.service.apache2]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package apache2"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "apache2"
package_install = false

[packages.service.mcstrans]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package mcstrans"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "mcstrans"
package_install = false

[packages.service.net-snmp]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package net-snmp"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "net-snmp"
package_install = false

[packages.service.snmp]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package snmp"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "snmp"
package_install = false

[packages.service.openssh-server]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package openssh-server"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "openssh-server"
package_install = true

[packages.service.rpcbind]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package rpcbind"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "rpcbind"
package_install = false

[packages.service.rsync]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package rsync"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "rsync"
package_install = false

[packages.service.samba]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package samba"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "samba"
package_install = false

[packages.service.squid]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package squid"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "squid"
package_install = false

[packages.service.nginx]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package nginx"
check_type = "package"
check_os = { amzn = ["2023"] }
package_name = "nginx"
package_install = false

[packages.service.nginx-core]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package nginx-core"
check_type = "package"
check_os = { ubuntu = ["22.04"] }
package_name = "nginx-core"
package_install = false

[packages.service.vsftpd]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package vsftpd"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "vsftpd"
package_install = false

[packages.time]
sub_category_audit = true
sub_category_harden = true
sub_category_name = "Time"

[packages.time.chrony]
check_audit = true
check_harden = true
check_id = ""
check_name = "Package chrony"
check_type = "package"
check_os = { amzn = ["2023"], ubuntu = ["22.04"] }
package_name = "chrony"
package_install = true

[system]
category_audit = true
category_harden = true
category_name = "System"
