#################################################
# Global Configuration
#################################################
[global]
# modprobe Configuration File Locations
modprobe_config = "/etc/modprobe.d/"

#################################################
# Filesystems Configuration
#################################################
[filesystems]
cramfs = "echo 'install cramfs /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
fat = "echo 'install fat /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
freevxfs = "echo 'install freevxfs /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
gfs2 = "echo 'install gfs2 /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
hfs = "echo 'install hfs /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
hfsplus = "echo 'install hfsplus /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
jffs2 = "echo 'install jffs2 /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
# nfs = "echo 'install nfs /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
# nfsv3 = "echo 'install nfsv3 /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
squashfs = "echo 'install squashfs /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
udf = "echo 'install udf /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
vfat = "echo 'install vfat /bin/false' >> /etc/modprobe.d/uncommon-fs.conf"
