#################################################
# Global Configuration
#################################################
[global]
# modprobe Configuration File Locations
modprobe_config = "/etc/modprobe.d/"
sysctl_config = "/etc/sysctl.d/"

#################################################
# Filesystems Configuration
#################################################
[filesystems.cramfs]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.fat]
skip = false
disable = false
cis = ""
disa = ""
mitre = ""
stig = ""
source = ""

[filesystems.freevxfs]
skip = false
disable = true
cis = "level-1"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.gfs2]
skip = false
disable = false
cis = ""
disa = ""
mitre = ""
stig = ""
source = ""

[filesystems.hfs]
skip = false
disable = true
cis = "level-1"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.hfsplus]
skip = false
disable = true
cis = "level-1"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.jffs2]
skip = false
disable = true
cis = "level-1"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.nfs]
skip = true
disable = false
cis = ""
disa = ""
mitre = ""
stig = ""
source = ""

[filesystems.nfsv3]
skip = true
disable = false
cis = ""
disa = ""
mitre = ""
stig = ""
source = ""

[filesystems.squashfs]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.udf]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1005,T1005.000 TA0005 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-7"

[filesystems.vfat]
skip = false
disable = false
cis = ""
disa = ""
mitre = ""
stig = ""
source = ""


#################################################
# Kernel Module Hardening
#################################################
[modules.dccp]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1068,T1068.000,T1210,T1210.000 TA0008 M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: SI-4, CM-7"

[modules.rds]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1068,T1068.000,T1210,T1210.000 TA0008 M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: SI-4, CM-7"

[modules.sctp]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1068,T1068.000,T1210,T1210.000 TA0008 M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: SI-4, CM-7"

[modules.tipc]
skip = false
disable = true
cis = "level-2"
disa = ""
mitre = "T1068,T1068.000,T1210,T1210.000 TA0008 M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: SI-4, CM-7"

#################################################
# Process Hardening
#################################################
[processes.aslr]
skip = false
set = true
stack = "kernel"
settings = ["kernel.randomize_va_space = 2"]
cis = "level-1"
disa = "CCI-000366"
mitre = "T1068,T1068.000 TA0002 M1050"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-6"

[processes.ptrace]
skip = false
set = true
stack = "kernel"
settings = ["kernel.yama.ptrace_scope = 1"]
cis = "level-1"
disa = ""
mitre = "T1055.008 TA0005 M1040"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-6"

#################################################
# Network Hardening
#################################################
# IPv4
[networks.ipv4forward]
skip = false
set = true
stack = "net"
settings = ["net.ipv4.ip_forward = 0"]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv4sendredirects]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.send_redirects = 0",
    "net.ipv4.conf.default.send_redirects = 0",
]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv4sourcerouteaccept]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.accept_source_route = 0",
    "net.ipv4.conf.default.accept_source_route = 0",
]
cis = "level-1"
disa = ""
mitre = "T1590,T1590.005 TA0007"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv4icmpredirectaccept]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.accept_redirects = 0",
    "net.ipv4.conf.default.accept_redirects = 0",
]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv4icmpsecureredirectaccept]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.secure_redirects = 0",
    "net.ipv4.conf.default.secure_redirects = 0",
]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.suspectpacketslogged]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.log_martians = 1",
    "net.ipv4.conf.default.log_martians = 1",
]
cis = "level-1"
disa = ""
mitre = "T1562,T1562.006 TA0005"
stig = ""
source = "NIST SP 800-53 Rev. 5: AU-3"

[networks.ignorebroadcastrequests]
skip = false
set = true
stack = "net"
settings = ["net.ipv4.icmp_echo_ignore_broadcasts = 1"]
cis = "level-1"
disa = ""
mitre = "T1498,T1498.001 TA0040 M1037"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ignorebogusicmpresponse]
skip = false
set = true
stack = "net"
settings = ["net.ipv4.icmp_ignore_bogus_error_responses = 1"]
cis = "level-1"
disa = ""
mitre = "T1562,T1562.006 TA0040 M1053"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.reversepathfilter]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv4.conf.all.rp_filter = 1",
    "net.ipv4.conf.default.rp_filter = 1",
]
cis = "level-1"
disa = ""
mitre = "T1498,T1498.001 TA0006,TA0040 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1,CM-2, CM-6, CM-7, IA-5"

[networks.tcpsyncookies]
skip = false
set = true
stack = "net"
settings = ["net.ipv4.tcp_syncookies = 1"]
cis = "level-1"
disa = ""
mitre = "T1499,T1499.001 TA0040 M1037"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1,CM-2, CM-6, CM-7, IA-5"

# IPv6
[networks.ipv6forward]
skip = false
set = true
stack = "net"
settings = ["net.ipv6.conf.all.forwarding = 0"]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv6sourcerouteaccept]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv6.conf.all.accept_source_route = 0",
    "net.ipv6.conf.default.accept_source_route = 0",
]
cis = "level-1"
disa = ""
mitre = "T1590,T1590.005 TA0007"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv6icmpredirectaccept]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv6.conf.all.accept_redirects = 0",
    "net.ipv6.conf.default.accept_redirects = 0",
]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0009 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1, CM-2, CM-6, CM-7, IA-5"

[networks.ipv6routeradvertisement]
skip = false
set = true
stack = "net"
settings = [
    "net.ipv6.conf.all.accept_ra = 0",
    "net.ipv6.conf.default.accept_ra = 0",
]
cis = "level-1"
disa = ""
mitre = "T1557,T1557.000 TA0006,TA0040 M1030,M1042"
stig = ""
source = "NIST SP 800-53 Rev. 5: CM-1,CM-2, CM-6, CM-7, IA-5"
