[accounts]
[accounts.0001a]
check_name = "/etc/passwd permissions configured"
check_type = "permissions"
check_path = "/etc/passwd"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0002a]
check_name = "/etc/passwd- permissions configured"
check_type = "permissions"
check_path = "/etc/passwd-"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0003a]
check_name = "/etc/group permissions configured"
check_type = "permissions"
check_path = "/etc/group"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0004a]
check_name = "/etc/group- permissions configured"
check_type = "permissions"
check_path = "/etc/group-"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0005a]
check_name = "/etc/shadow permissions configured"
check_type = "permissions"
check_path = "/etc/shadow"
expected_gid = 0
expected_permissions = 0
expected_uid = 0
valid_os = ["amzn-2023"]

[accounts.0005b]
check_name = "/etc/shadow permissions configured"
check_type = "permissions"
check_path = "/etc/shadow"
expected_gid = 42
expected_permissions = 640
expected_uid = 0
valid_os = ["debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0006a]
check_name = "/etc/shadow- permissions configured"
check_type = "permissions"
check_path = "/etc/shadow-"
expected_gid = 0
expected_permissions = 0
expected_uid = 0
valid_os = ["amzn-2023"]

[accounts.0006b]
check_name = "/etc/shadow- permissions configured"
check_type = "permissions"
check_path = "/etc/shadow-"
expected_gid = 42
expected_permissions = 640
expected_uid = 0
valid_os = ["debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0007a]
check_name = "/etc/gshadow permissions configured"
check_type = "permissions"
check_path = "/etc/gshadow"
expected_gid = 0
expected_permissions = 0
expected_uid = 0
valid_os = ["amzn-2023"]

[accounts.0007b]
check_name = "/etc/gshadow permissions configured"
check_type = "permissions"
check_path = "/etc/gshadow"
expected_gid = 42
expected_permissions = 640
expected_uid = 0
valid_os = ["debian-12", "kali-2024.1", "ubuntu-22.04"]

[accounts.0008a]
check_name = "/etc/gshadow- permissions configured"
check_type = "permissions"
check_path = "/etc/gshadow-"
expected_gid = 0
expected_permissions = 0
expected_uid = 0
valid_os = ["amzn-2023"]

[accounts.0008b]
check_name = "/etc/gshadow- permissions configured"
check_type = "permissions"
check_path = "/etc/gshadow-"
expected_gid = 42
expected_permissions = 640
expected_uid = 0
valid_os = ["debian-12", "kali-2024.1", "ubuntu-22.04"]

[aide]
[aide.0001a]
check_name = "aide"
check_type = "package"
package_name = "aide"
package_status = "install"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[audit]
[audit.0001a]
check_name = "audit"
check_type = "package"
package_name = "audit"
package_status = "install"
valid_os = ["amzn-2023"]

[audit.0001b]
check_name = "auditd"
check_type = "package"
package_name = "auditd"
package_status = "install"
valid_os = ["ubuntu-22.04"]

[banners]
[banners.0001a]
check_name = "/etc/motd permissions configured"
check_type = "permissions"
check_path = "/etc/motd"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[banners.0002a]
check_name = "/etc/issue permissions configured"
check_type = "permissions"
check_path = "/etc/issue"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[banners.0003a]
check_name = "/etc/issue.net permissions configured"
check_type = "permissions"
check_path = "/etc/issue.net"
expected_gid = 0
expected_permissions = 644
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]


[filesystem]
[filesystem.mounts]
[filesystem.mounts.0001a]
check_name = "/tmp separate partition"
check_type = "mount-point"
check_path = "/tmp"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0001b]
check_name = "/tmp mount options not set"
check_type = "mount-options"
check_path = "/tmp"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0002a]
check_name = "/var separate partition"
check_type = "mount-point"
check_path = "/var"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0002b]
check_name = "/var mount options not set"
check_type = "mount-options"
check_path = "/var"
mount_options = ["nodev", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0003a]
check_name = "/var/tmp separate partition"
check_type = "mount-point"
check_path = "/var/tmp"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0003b]
check_name = "/var/tmp mount options not set"
check_type = "mount-options"
check_path = "/var/tmp"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0004a]
check_name = "/var/log separate partition"
check_type = "mount-point"
check_path = "/var/log"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0004b]
check_name = "/var/log mount options not set"
check_type = "mount-options"
check_path = "/var/log"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0005a]
check_name = "/var/log/audit separate partition"
check_type = "mount-point"
check_path = "/var/log/audit"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0005b]
check_name = "/var/log/audit mount options not set"
check_type = "mount-options"
check_path = "/var/log/audit"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0006a]
check_name = "/home separate partition"
check_type = "mount-point"
check_path = "/home"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0006b]
check_name = "/home mount options not set"
check_type = "mount-options"
check_path = "/home"
mount_options = ["nodev", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0007a]
check_name = "/dev/shm separate partition"
check_type = "mount-point"
check_path = "/dev/shm"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]

[filesystem.mounts.0007b]
check_name = "/dev/shm mount options not set"
check_type = "mount-options"
check_path = "/dev/shm"
mount_options = ["nodev", "noexec", "nosuid"]
valid_os = ["amzn-2023", "ubuntu-22.04"]


[kernel]

[kernel.modules]
[kernel.modules.0001a]
check_name = "cramfs"
check_type = "kernel-module"
module_name = "cramfs"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0002a]
check_name = "dccp"
check_type = "kernel-module"
module_name = "dccp"
module_type = "network"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0003a]
check_name = "freevxfs"
check_type = "kernel-module"
module_name = "freevxfs"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0004a]
check_name = "hfs"
check_type = "kernel-module"
module_name = "hfs"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0005a]
check_name = "hfsplus"
check_type = "kernel-module"
module_name = "hfsplus"
module_type = "filesystem"
valid_os = ["ubuntu-22.04"]

[kernel.modules.0006a]
check_name = "jffs2"
check_type = "kernel-module"
module_name = "jffs2"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0007a]
check_name = "rds"
check_type = "kernel-module"
module_name = "rds"
module_type = "network"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0008a]
check_name = "sctp"
check_type = "kernel-module"
module_name = "sctp"
module_type = "network"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0009a]
check_name = "squashfs"
check_type = "kernel-module"
module_name = "squashfs"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0010a]
check_name = "tipc"
check_type = "kernel-module"
module_name = "tipc"
module_type = "network"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0011a]
check_name = "udf"
check_type = "kernel-module"
module_name = "udf"
module_type = "filesystem"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.modules.0012a]
check_name = "usb-storage"
check_type = "kernel-module"
module_name = "usb-storage"
module_type = "storage"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[kernel.parameters]
[kernel.parameters.0001a]
check_name = "testing-param1"
check_type = "kernel-parameter"
check_path = ""
instance_type = ""
parameter_type = ""
valid_os = ["amzn-2023", "ubuntu-22.04"]

[logging]
[logging.rsyslog]
[logging.rsyslog.0001a]
check_name = "rsyslog"
check_type = "package"
package_name = "rsyslog"
package_status = "install"
valid_os = ["amzn-2023"]


[restricted]

[restricted.packages]
[restricted.packages.0001a]
check_name = "avahi"
check_type = "package"
package_name = "avahi"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0001b]
check_name = "avahi-daemon"
check_type = "package"
package_name = "avahi-daemon"
package_status = "remove"
valid_os = ["ubuntu-22.04"]

[restricted.packages.0002a]
check_name = "bind"
check_type = "package"
package_name = "bind"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0002b]
check_name = "bind9"
check_type = "package"
package_name = "bind9"
package_status = "remove"
valid_os = ["ubuntu-22.04"]

[restricted.packages.0003a]
check_name = "cups"
check_type = "package"
package_name = "cups"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0004a]
check_name = "dnsmasq"
check_type = "package"
package_name = "dnsmasq"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0005a]
check_name = "dovecot"
check_type = "package"
package_name = "dovecot"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0006a]
check_name = "httpd"
check_type = "package"
package_name = "httpd"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0007a]
check_name = "net-snmp"
check_type = "package"
package_name = "net-snmp"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0008a]
check_name = "nfs-utils"
check_type = "package"
package_name = "nfs-utils"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0009a]
check_name = "nginx"
check_type = "package"
package_name = "nginx"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0010a]
check_name = "openldap-clients"
check_type = "package"
package_name = "openldap-clients"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0011a]
check_name = "rpcbind"
check_type = "package"
package_name = "rpcbind"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0012a]
check_name = "rsync-daemon"
check_type = "package"
package_name = "rsync-daemon"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0013a]
check_name = "samba"
check_type = "package"
package_name = "samba"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0014a]
check_name = "squid"
check_type = "package"
package_name = "squid"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0015a]
check_name = "telnet"
check_type = "package"
package_name = "telnet"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0016a]
check_name = "telnet-server"
check_type = "package"
package_name = "telnet-server"
package_status = "remove"
valid_os = ["amzn-2023"]

[restricted.packages.0017a]
check_name = "vsftpd"
check_type = "package"
package_name = "vsftpd"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[restricted.packages.0018a]
check_name = "xorg-x11-server-common"
check_type = "package"
package_name = "xorg-x11-server-common"
package_status = "remove"
valid_os = ["amzn-2023"]

# Testing package
[restricted.packages.000001a]
check_name = "xauth"
check_type = "package"
package_name = "xauth"
package_status = "remove"
valid_os = ["amzn-2023", "ubuntu-22.04"]


[restricted.services]
[restricted.services.00000001a]
check_name = "avahi-daemon.service"
check_type = "service"
service_name = "avahi-daemon.service"
service_status = "masked"                # enabled | disabled | masked
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers]
[schedulers.at]
[schedulers.at.0001a]
check_name = "at"
check_type = "package"
package_name = "at"
package_status = "install"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.at.0002a]
check_name = "atd.service"
check_type = "service"
service_name = "atd.service"
service_status = "enabled"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.at.0003a]
check_name = "/etc/at.allow exists"
check_type = "file-exists"
check_path = "/etc/at.allow"
file_exists = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.at.0004a]
check_name = "/etc/at.deny exists"
check_type = "file-exists"
check_path = "/etc/at.deny"
file_exists = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron]
[schedulers.cron.0001a]
check_name = "cronie"
check_type = "package"
package_name = "cronie"
package_status = "install"
valid_os = ["amzn-2023"]

[schedulers.cron.0001b]
check_name = "cron"
check_type = "package"
package_name = "cron"
package_status = "install"
valid_os = ["ubuntu-22.04"]

[schedulers.cron.0002a]
check_name = "cron.service"
check_type = "service"
service_name = "cron.service"
service_status = "enabled"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0003a]
check_name = "/etc/cron.allow exists"
check_type = "file-exists"
check_path = "/etc/cron.allow"
file_exists = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0004a]
check_name = "/etc/cron.deny exists"
check_type = "file-exists"
check_path = "/etc/cron.deny"
file_exists = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0005a]
check_name = "/etc/crontab permissions configured"
check_type = "permissions"
check_path = "/etc/crontab"
expected_gid = 0
expected_permissions = 600
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0006a]
check_name = "/etc/cron.hourly permissions configured"
check_type = "permissions"
check_path = "/etc/cron.hourly"
expected_gid = 0
expected_permissions = 700
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0007a]
check_name = "/etc/cron.daily permissions configured"
check_type = "permissions"
check_path = "/etc/cron.daily"
expected_gid = 0
expected_permissions = 700
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0008a]
check_name = "/etc/cron.weekly permissions configured"
check_type = "permissions"
check_path = "/etc/cron.weekly"
expected_gid = 0
expected_permissions = 700
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0009a]
check_name = "/etc/cron.monthly permissions configured"
check_type = "permissions"
check_path = "/etc/cron.monthly"
expected_gid = 0
expected_permissions = 700
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[schedulers.cron.0010a]
check_name = "/etc/cron.d permissions configured"
check_type = "permissions"
check_path = "/etc/cron.d"
expected_gid = 0
expected_permissions = 700
expected_uid = 0
valid_os = ["amzn-2023", "ubuntu-22.04"]

[selinux]
[selinux.0001a]
check_name = "libselinux"
check_type = "package"
package_name = "libselinux"
package_status = "install"
valid_os = ["amzn-2023"]

[sudo]
[sudo.0001a]
check_name = "sudo"
check_type = "package"
package_name = "sudo"
package_status = "install"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[time]
[time.chrony]
[time.chrony.0001a]
check_name = "chrony"
check_type = "package"
package_name = "chrony"
package_status = "install"
valid_os = ["amzn-2023", "ubuntu-22.04"]

[time.systemd-timesyncd]
[time.systemd-timesyncd.0001a]
check_name = "systemd-timesyncd"
check_type = "package"
package_name = "systemd-timesyncd"
package_status = "install"
valid_os = ["ubuntu-22.04"]
