[modules]

[modules.cramfs]
module_name = "cramfs"

[modules.freevxfs]
module_name = "freevxfs"

[modules.hfs]
module_name = "hfs"

[modules.hfsplus]
module_name = "hfsplus"

[modules.jffs2]
module_name = "jffs2"

[modules.squashfs]
module_name = "squashfs"

[modules.udf]
module_name = "udf"

[modules.usbstorage]
module_name = "usb_storage"
