[config_files]
sshd = [
    "/etc/ssh/test",
    "/etc/ssh/testing",
    "/etc/ssh/sshd_config",
    "/etc/ssh/sshd_config.d",
]

sysctl = [
    "/run/sysctl.d/*.conf",
    "/etc/sysctl.d/*.conf",
    "/usr/local/lib/sysctl.d/*.conf",
    "/usr/lib/sysctl.d/*.conf",
    "/lib/sysctl.d/*.conf",
    "/etc/sysctl.conf",
]

[pkgmgr]
amzn = "dnf list installed"
debian = ""
fedora = ""
kali = ""
rhel = ""
rocky = ""
ubuntu = "dpkg-query -l"
