[config_files]
aide = ["/etc/aide.conf", "/etc/aide.conf.d/"]
chrony = ["/etc/chrony.conf", "/etc/chrony.d"]
coredump = ["/etc/systemd/coredump.conf", "/etc/systemd/coredump.conf.d"]
crypto = [
    "/etc/crypto-policies/config",
    "/etc/crypto-policies/local.d",
    "/etc/crypto-policies/policies",
    "/usr/share/crypto-policies/policies",
]
gpg = ["/etc/dnf/dnf.conf", "/etc/yum.repos.d"]
kernel = [
    "/etc/modprobe.d/*.conf",
    "/lib/modprobe.d/*.conf",
    "/run/modprobe.d/*.conf",
    "/usr/local/lib/modprobe.d/*.conf",
]
selinux = ["/etc/selinux/config"]
shell = ["/etc/bashrc", "/etc/profile", "/etc/profile.d"]
sshd = ["/etc/ssh/sshd_config", "/etc/ssh/sshd_config.d", "/etc/ssh/test"]
sudo = ["/etc/sudoers", "/etc/sudoers.d"]
sysctl = [
    "/etc/sysctl.conf",
    "/etc/sysctl.d/",
    "/lib/sysctl.d/",
    "/run/sysctl.d/",
    "/usr/lib/sysctl.d/",
    "/usr/local/lib/sysctl.d/",
]
umask = ["/etc/bashrc", "/etc/login.defs", "/etc/profile", "/etc/profile.d"]
