[config_files]
sshd = ["/etc/ssh/sshd_config", "/etc/ssh/sshd_config.d"]
sudo = ["/etc/sudoers", "/etc/sudoers.d"]
sysctl = [
    "/run/sysctl.d/",
    "/etc/sysctl.d/",
    "/usr/local/lib/sysctl.d/",
    "/usr/lib/sysctl.d/",
    "/lib/sysctl.d/",
    "/etc/sysctl.conf",
]

[pkgmgr]
amzn = "dnf list installed"
debian = ""
fedora = ""
kali = ""
rhel = ""
rocky = ""
ubuntu = "dpkg-query -l"
