[package]
[package.0001a]
check_name = "avahi package"
check_type = "package"
package_name = "avahi"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0002a]
check_name = "bind package"
check_type = "package"
package_name = "bind"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0003a]
check_name = "cups package"
check_type = "package"
package_name = "cups"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0004a]
check_name = "dnsmasq package"
check_type = "package"
package_name = "dnsmasq"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0005a]
check_name = "dovecot package"
check_type = "package"
package_name = "dovecot"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0006a]
check_name = "httpd package"
check_type = "package"
package_name = "httpd"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0007a]
check_name = "lftp package"
check_type = "package"
package_name = "lftp"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0008a]
check_name = "mcstrans package"
check_type = "package"
package_name = "mcstrans"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0009a]
check_name = "net-snmp package"
check_type = "package"
package_name = "net-snmp"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0010a]
check_name = "nfs-utils package"
check_type = "package"
package_name = "nfs-utils"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0011a]
check_name = "nginx package"
check_type = "package"
package_name = "nginx"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0012a]
check_name = "openldap-clients package"
check_type = "package"
package_name = "openldap-clients"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0013a]
check_name = "rpcbind package"
check_type = "package"
package_name = "rpcbind"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0014a]
check_name = "rsync-daemon package"
check_type = "package"
package_name = "rsync-daemon"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0015a]
check_name = "samba package"
check_type = "package"
package_name = "samba"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0016a]
check_name = "squid package"
check_type = "package"
package_name = "squid"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0017a]
check_name = "telnet package"
check_type = "package"
package_name = "telnet"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0018a]
check_name = "telnet-server package"
check_type = "package"
package_name = "telnet-server"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0019a]
check_name = "vsftpd package"
check_type = "package"
package_name = "vsftpd"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[package.0020a]
check_name = "xorg-x11-server-common package"
check_type = "package"
package_name = "xorg-x11-server-common"
package_installed = false
valid_os = ["amzn-2023", "ubuntu-22.04"]











[service]
[service.0003a]
check_name = "avahi-daemon.service"
check_type = "service"
service_name = "avahi-daemon.service"
service_enabled = false
service_active = false
service_masked = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0004a]
check_name = "avahi-daemon.socket"
check_type = "service"
service_name = "avahi-daemon.socket"
service_enabled = false
service_active = false
service_masked = false
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0006a]
check_name = "nfs-server"
check_type = "service"
service_name = "nfs-server"
service_enabled = false
service_active = false
service_masked = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0007a]
check_name = "rpcbind.service"
check_type = "service"
service_name = "rpcbind.service"
service_enabled = false
service_active = false
service_masked = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0008a]
check_name = "rpcbind.socket"
check_type = "service"
service_name = "rpcbind.socket"
service_enabled = false
service_active = false
service_masked = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0009a]
check_name = "rsyncd"
check_type = "service"
service_name = "rsyncd"
service_enabled = false
service_active = false
service_masked = true
valid_os = ["amzn-2023", "ubuntu-22.04"]

[service.0011a]
check_name = "snmpd"
check_type = "service"
service_name = "snmpd"
service_enabled = false
service_active = false
service_masked = true
valid_os = ["amzn-2023", "ubuntu-22.04"]













