name: Release
on:
    push:
        branches:
            - release

jobs:
    publish:
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]
                poetry-version: ["1.6.1"]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Build and publish to pypi
              uses: JRubics/poetry-publish@v1.17
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
